name: Deploy to AWS EC2

on:
  workflow_dispatch:

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # Build and push new docker image, skip for manual redeploy other than 'latest'
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
  
  deploy:
    needs: push_to_registry
    runs-on: ubuntu-latest
    steps:
       
        - name: Copy docker-compose file to target server
          uses: appleboy/scp-action@v0.1.3
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            port: 22
            key: ${{ secrets.EC2_SSH_KEY }}
            source: "./compose.prod.yml"
            target: "/home/${{ secrets.EC2_USER }}/app"

        - name: SSH into EC2 and Deploy
          uses: appleboy/ssh-action@v0.1.6
          env:
            IMAGE_REPO: "ghcr.io/${{ github.repository }}:latest"
            GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
            GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
            CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
                set -e
                echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

                cd /home/${{ secrets.EC2_USER }}/app           
                
                docker compose -f compose.prod.yml up -d --pull always --remove-orphans --force-recreate